// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use env vars if set, otherwise fallback to project defaults
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://aocqfveoztmwntoexkpj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvY3FmdmVvenRtd250b2V4a3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjMyNDQsImV4cCI6MjA2NDk5OTI0NH0.BdDJP40QF5yg0maBakYRxbV4skbwd_lDzye57QIs8PE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);